### ISSUE TITLE
Newer discord list

### ISSUE THREAD

**Issue by bartMarinissen** [Inne-Lemstra/LAN_game_detect#1]
I pulled this straight from the current JS code of discord. You may need to add some slight formatting.

[new 1.txt](https://github.com/Inne-Lemstra/LAN_game_detect/files/797535/new.1.txt)

**Comment by Inne-Lemstra** [comment]
Thx, the format is slightly different form the current list.
But I'll find a way to convert it.

**Comment by Inne-Lemstra** [comment]
Turns out that this is the same as all_the_games list was using.
(tested same amount of entries, and a frighteningly similar ordering (after add/ reformat))
